# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from pathlib import Path
sys.path.insert(0, os.path.abspath(Path(__file__.rsplit('/', 1)[0]) /  '..' / '..' / 'yeastr'))
sys.path.append(str(Path('_ext').resolve()))

import yeastr.bootstrapped
import yeastr.as_decorator
import yeastr.import_hooks

# REMEMBER TO ADD THEM TO implemetation_reference.rst
for rstfile in ('bootstrapped', 'as_decorator', 'import_hooks', 'interactive', 'py39unparser', 'stabilize_ast_for_ci'):
    path = __file__.replace('conf.py', f'a_{rstfile}.rst')
    with open(path, 'w') as out:
        out.write(f'''
.. 
    this file is auto-generated by conf.py

yeastr.{rstfile}
{'-' * len(f"yeastr.{rstfile}")}

.. automodule:: yeastr.{rstfile}
   :members:
   :undoc-members:
   :member-order: bysource
   :show-inheritance:
   :noindex:
''')

# REMEMBER TO ADD THEM TO internal_documentation.rst
yrstfiles = [
    {
        'path': '../yeastr/yeastr/utils.py',
        'module': 'yeastr.utils',
        'rstpath': 'y_utils.rst',
        'title': 'Utils',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/shared.ypy',
        'module': 'yeastr.shared',
        'rstpath': 'y_shared.rst',
        'title': 'Shared',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/impl_macros.pyy',
        'module': 'yeastr.impl_macros',
        'rstpath': 'y_impl_macros.rst',
        'title': 'Macro Implementation',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/impl_namedloops.pyy',
        'module': 'yeastr.impl_namedloops',
        'rstpath': 'y_impl_namedloops.rst',
        'title': 'Named Loops Implementation',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/impl_call2comp.pyy',
        'module': 'yeastr.impl_call2comp',
        'rstpath': 'y_impl_call2comp.rst',
        'title': 'call2comp Implementation',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/backport_match.pyy',
        'module': 'yeastr.backport_match',
        'rstpath': 'y_backport_match.rst',
        'title': 'Backport Structural Pattern Matching',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/backport_fstring_backslash.pyy',
        'module': 'yeastr.backport_fstring_backslash',
        'rstpath': 'y_backport_fstring_bs.rst',
        'title': 'Backport ``f"{\'\\n\'}"``',
        'description': 'See PEP701',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/backport_dict_ops.pyy',
        'module': 'yeastr.backport_dict_ops',
        'rstpath': 'y_backport_dict_merge.rst',
        'title': 'Backport ``|=`` and ``|`` over dict',
        'description': 'PEP584, Really limited implementation',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/build_time_transformer.pyy',
        'module': 'yeastr.build_time_transformer',
        'rstpath': 'y_build_time_transformer.rst',
        'title': 'Build time transformer',
        'description': 'Composition through the previously defined macros',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/yam.ypy',
        'module': 'yeastr.yam',
        'rstpath': 'y_yam.rst',
        'title': 'Ast Matchers',
        'description': '',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/as_decorators.pyy',
        'module': 'yeastr.as_decorators',
        'rstpath': 'y_as_decorators.rst',
        'title': 'As Decorators',
        'description': 'An alternative usage of yeastr',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/import_hooks.pyy',
        'module': 'yeastr.import_hooks',
        'rstpath': 'y_import_hooks.rst',
        'title': 'Import Hooks',
        'description': 'An alternative kinda interactive usage of yeastr',
        'members': True,
    },
    {
        'path': '../yeastr/yeastr/interactive.py',
        'module': 'yeastr.interactive',
        'rstpath': 'y_interactive.rst',
        'title': 'REPL',
        'description': 'Interactive yeastr REPL',
        'members': True,
    },
]
for rstfile in yrstfiles:
    path = __file__.replace('conf.py', rstfile['rstpath'])
    with open(path, 'w') as out:
        out.write(f'''
.. 
    this file is auto-generated by conf.py

{rstfile['title']}
{'-' * len(rstfile['title'])}

{rstfile['description']}

.. yeastr:: {rstfile['path']}
    :module: {rstfile['module']}
    :members: {rstfile['members']}
''')

#yeastr.__loader__.get_resource_reader(yeastr).files()

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'yeastr'
copyright = '2025, CAST'
author = 'CAST'
release = '0.0.2'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.graphviz',
    # 'sphinx.ext.githubpages',  # doesn't work
    'yeastr_quasiautodocs',
]

templates_path = ['_templates']
exclude_patterns = []



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']
html_css_files = ['custom.css']

# -- Options for todo extension ----------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/todo.html#configuration

todo_include_todos = True
